import { Injectable, effect, signal } from '@angular/core';

export type LanguageCode = 'es' | 'en';

const STORAGE_KEY = 'geovistaLanguage';

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  es: {
    'common.home': 'Inicio',
    'common.maps': 'Mapas',
    'common.argis': 'Argis',
    'common.theme': 'Tema',
    'common.language': 'Idioma',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.cancel': 'Cancelar',
    'common.createdBy': 'Creado por Victor M Carmona Moraza',

    'login.title': 'Acceso a GeoVista',
    'login.subtitle': 'Inicia sesion para usar mapas y analisis Argis',
    'login.user': 'Usuario',
    'login.password': 'Contrasena',
    'login.submit': 'Entrar',
    'login.hint': 'Credenciales por defecto: admin / Admin123!',
    'login.invalidCredentials': 'Credenciales invalidas. Intentalo de nuevo.',
    'login.logout': 'Cerrar sesion',
    'login.registerTitle': 'Registrar usuario',
    'login.registerUser': 'Nuevo usuario',
    'login.registerPassword': 'Nueva contrasena',
    'login.registerButton': 'Crear cuenta',
    'login.registerExists': 'Ese usuario ya existe.',
    'login.registerInvalid': 'Usuario minimo 3 caracteres y contrasena minimo 6.',
    'login.registerSuccess': 'Usuario creado. Ya puedes iniciar sesion.',

    'home.subtitle': 'Exploracion cartografica interactiva',
    'home.description': 'Visualiza mapas del mundo, analiza capas geoespaciales y explora datos geograficos en tiempo real.',
    'home.exploreMaps': 'Explorar Mapas',
    'home.argisAnalysis': 'Analisis Argis',

    'maps.headerDescription': 'Mapas interactivos con Leaflet, Angular y Tailwind CSS',
    'maps.title': 'Atlas Interactivo',
    'maps.controls': 'Controles',
    'maps.searchCity': 'Buscar ciudad',
    'maps.searchPlaceholder': 'Escribe una ciudad...',
    'maps.searching': 'Buscando...',
    'maps.zoom': 'Zoom',
    'maps.zoomIn': '+ Acercar',
    'maps.zoomOut': '- Alejar',
    'maps.layers': 'Capas',
    'maps.changeLayer': 'Cambiar capa',
    'maps.goToCity': 'Ir a ciudad',
    'maps.myNotes': 'Mis notas',
    'maps.addNoteQuestion': '¿Quieres añadir una nota a esta ubicacion?',
    'maps.notePlaceholder': 'Escribe una nota... (opcional)',
    'maps.markOnly': 'Solo marcar',
    'maps.saveNote': 'Guardar nota',
    'maps.viewAllNotes': 'Ver todas las notas',
    'maps.notesPageTitle': 'Notas guardadas',
    'maps.notesPageDescription': 'Consulta todas las notas registradas por el usuario actual.',
    'maps.notesByUser': 'Usuario: {{username}}',
    'maps.noNotes': 'Todavia no hay notas guardadas para este usuario.',
    'maps.noteSavedOn': 'Guardada el {{date}}',
    'maps.notesLoadError': 'No se pudieron cargar las notas guardadas.',
    'maps.backToMap': 'Volver al mapa',
    'maps.deleteNote': 'Eliminar nota',
    'maps.deleteConfirm': '¿Seguro que quieres eliminar esta nota?',
    'maps.deleteError': 'No se pudo eliminar la nota.',
    'maps.backHomeTitle': 'Volver al inicio',
    'maps.searchNoResults': 'No se encontraron resultados.',
    'maps.searchError': 'Error al buscar. Verifica tu conexion.',

    'argis.headerDescription': 'Carga y visualizacion de shapefiles',
    'argis.uploadShapefile': 'Subir shapefile',
    'argis.loadExample': 'Cargar ejemplo',
    'argis.showCcaa': 'Mostrar CCAA',
    'argis.hideCcaa': 'Ocultar CCAA',
    'argis.showWorld': 'Mostrar Mundo',
    'argis.hideWorld': 'Ocultar Mundo',
    'argis.open3d': 'Ver 3D',
    'argis.view3d': 'Argis 3D',
    'argis.back2d': 'Volver a Argis 2D',
    'argis.threeDDescription': 'Exploracion del terreno con relieve y camara 3D',
    'argis.acceptedFormats': 'Aceptado: .zip o conjunto .shp + .dbf + .shx (opcional: .prj/.cpg).',
    'argis.searchPlaceholder': 'Buscar pueblo y saltar al mapa...',
    'argis.placeInfoTitle': 'Informacion del lugar',
    'argis.placeInfoDescriptionFallback': 'No hay una descripcion ampliada disponible para este lugar, pero puedes usar esta ficha como referencia rapida en el mapa.',
    'argis.placeCoordinates': 'Coordenadas',
    'argis.placeImageAlt': 'Imagen de {{place}}',
    'argis.loadingLayer': 'Cargando capa...',
    'argis.legend': 'Leyenda:',
    'argis.africa': 'Africa',
    'argis.asia': 'Asia',
    'argis.europe': 'Europa',
    'argis.northAmerica': 'America del Norte',
    'argis.southAmerica': 'America del Sur',
    'argis.oceania': 'Oceania',
    'argis.antarctica': 'Antartida',
    'argis.initialStatus': 'Sube un .zip o selecciona el conjunto de shapefile (.shp + .dbf + .shx).',
    'argis.defaultWorldLoaded': 'GeoJSON mundial cargado por defecto.',
    'argis.defaultWorldFailed': 'Mapa base listo. No se pudo cargar el GeoJSON mundial por defecto.',
    'argis.processingFiles': 'Procesando {{count}} archivo(s)...',
    'argis.fileLoadError': 'Error en la carga del fichero.',
    'argis.mapInitializing': 'El mapa todavia se esta inicializando. Vuelve a pulsar en unos segundos.',
    'argis.loadingExample': 'Cargando capa de ejemplo...',
    'argis.exampleLoaded': 'Capa de tuberias de agua cargada correctamente.',
    'argis.exampleLoadError': 'Error al cargar la capa de ejemplo.',
    'argis.exampleLoadErrorDetail': 'No se pudo cargar la capa de ejemplo.',
    'argis.ccaaHidden': 'Capa de comunidades autonomas oculta.',
    'argis.loadingCcaa': 'Cargando limites de comunidades autonomas...',
    'argis.ccaaLoaded': 'Limites de comunidades autonomas cargados.',
    'argis.ccaaTip': 'Pulsa una comunidad autonoma para ver sus provincias.',
    'argis.ccaaLoadError': 'Error al cargar comunidades autonomas.',
    'argis.ccaaLoadErrorDetail': 'No se pudieron cargar los limites de comunidades autonomas.',
    'argis.loadingCommunity': 'Cargando {{community}} y sus provincias...',
    'argis.communityReady': 'Mostrando {{community}} con divisiones por provincias.',
    'argis.communityNoProvinces': 'No se pudieron obtener provincias para {{community}}.',
    'argis.communityLoadError': 'No se pudo centrar la comunidad seleccionada.',
    'argis.worldHidden': 'Capa mundial oculta.',
    'argis.loadingWorld': 'Cargando GeoJSON mundial...',
    'argis.worldLoaded': 'GeoJSON mundial cargado correctamente.',
    'argis.worldLoadError': 'Error al cargar la capa mundial.',
    'argis.worldLoadErrorDetail': 'No se pudo cargar el GeoJSON mundial.',
    'argis.layerUnsupported': 'La capa no contiene geometrias compatibles (lineas, poligonos o puntos).',
    'argis.polygonLayerLoaded': 'Capa poligonal cargada (limites/areas urbanas).',
    'argis.pointLayerLoaded': 'Capa de puntos cargada (poblaciones/lugares).',
    'argis.lineLayerLoaded': 'Capa lineal cargada correctamente.',
    'argis.placeNotFound': 'No se encontro el lugar indicado.',
    'argis.showingPlace': 'Mostrando: {{place}}.',
    'argis.searchPlaceError': 'No se pudo buscar ese lugar en este momento.',
    'argis.readShapefileError': 'No se pudo leer el shapefile. Usa .zip o selecciona al menos .shp + .dbf + .shx.',
  },
  en: {
    'common.home': 'Home',
    'common.maps': 'Maps',
    'common.argis': 'Argis',
    'common.theme': 'Theme',
    'common.language': 'Language',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.createdBy': 'Created by Victor M Carmona Moraza',

    'login.title': 'GeoVista Access',
    'login.subtitle': 'Sign in to use maps and Argis analysis',
    'login.user': 'User',
    'login.password': 'Password',
    'login.submit': 'Sign in',
    'login.hint': 'Default credentials: admin / Admin123!',
    'login.invalidCredentials': 'Invalid credentials. Please try again.',
    'login.logout': 'Sign out',
    'login.registerTitle': 'Register user',
    'login.registerUser': 'New user',
    'login.registerPassword': 'New password',
    'login.registerButton': 'Create account',
    'login.registerExists': 'That user already exists.',
    'login.registerInvalid': 'Username min 3 chars and password min 6.',
    'login.registerSuccess': 'User created. You can now sign in.',

    'home.subtitle': 'Interactive cartographic exploration',
    'home.description': 'Visualize world maps, analyze geospatial layers and explore geographic data in real time.',
    'home.exploreMaps': 'Explore Maps',
    'home.argisAnalysis': 'Argis Analysis',

    'maps.headerDescription': 'Interactive maps with Leaflet, Angular and Tailwind CSS',
    'maps.title': 'Interactive Atlas',
    'maps.controls': 'Controls',
    'maps.searchCity': 'Search city',
    'maps.searchPlaceholder': 'Type a city...',
    'maps.searching': 'Searching...',
    'maps.zoom': 'Zoom',
    'maps.zoomIn': '+ Zoom in',
    'maps.zoomOut': '- Zoom out',
    'maps.layers': 'Layers',
    'maps.changeLayer': 'Change layer',
    'maps.goToCity': 'Go to city',
    'maps.myNotes': 'My notes',
    'maps.addNoteQuestion': 'Do you want to add a note to this location?',
    'maps.notePlaceholder': 'Write a note... (optional)',
    'maps.markOnly': 'Mark only',
    'maps.saveNote': 'Save note',
    'maps.viewAllNotes': 'View all notes',
    'maps.notesPageTitle': 'Saved notes',
    'maps.notesPageDescription': 'Review all notes stored for the current user.',
    'maps.notesByUser': 'User: {{username}}',
    'maps.noNotes': 'There are no saved notes for this user yet.',
    'maps.noteSavedOn': 'Saved on {{date}}',
    'maps.notesLoadError': 'Saved notes could not be loaded.',
    'maps.backToMap': 'Back to map',
    'maps.deleteNote': 'Delete note',
    'maps.deleteConfirm': 'Are you sure you want to delete this note?',
    'maps.deleteError': 'The note could not be deleted.',
    'maps.backHomeTitle': 'Back to home',
    'maps.searchNoResults': 'No results found.',
    'maps.searchError': 'Search failed. Check your connection.',

    'argis.headerDescription': 'Upload and visualize shapefiles',
    'argis.uploadShapefile': 'Upload shapefile',
    'argis.loadExample': 'Load example',
    'argis.showCcaa': 'Show Regions',
    'argis.hideCcaa': 'Hide Regions',
    'argis.showWorld': 'Show World',
    'argis.hideWorld': 'Hide World',
    'argis.open3d': 'View 3D',
    'argis.view3d': 'Argis 3D',
    'argis.back2d': 'Back to Argis 2D',
    'argis.threeDDescription': 'Terrain exploration with elevation and 3D camera',
    'argis.acceptedFormats': 'Accepted: .zip or .shp + .dbf + .shx set (optional: .prj/.cpg).',
    'argis.searchPlaceholder': 'Search town and jump to map...',
    'argis.placeInfoTitle': 'Place information',
    'argis.placeInfoDescriptionFallback': 'There is no extended description available for this place, but you can use this card as a quick reference on the map.',
    'argis.placeCoordinates': 'Coordinates',
    'argis.placeImageAlt': 'Image of {{place}}',
    'argis.loadingLayer': 'Loading layer...',
    'argis.legend': 'Legend:',
    'argis.africa': 'Africa',
    'argis.asia': 'Asia',
    'argis.europe': 'Europe',
    'argis.northAmerica': 'North America',
    'argis.southAmerica': 'South America',
    'argis.oceania': 'Oceania',
    'argis.antarctica': 'Antarctica',
    'argis.initialStatus': 'Upload a .zip or select the shapefile set (.shp + .dbf + .shx).',
    'argis.defaultWorldLoaded': 'World GeoJSON loaded by default.',
    'argis.defaultWorldFailed': 'Base map ready. The default world GeoJSON could not be loaded.',
    'argis.processingFiles': 'Processing {{count}} file(s)...',
    'argis.fileLoadError': 'File load error.',
    'argis.mapInitializing': 'The map is still initializing. Please try again in a few seconds.',
    'argis.loadingExample': 'Loading example layer...',
    'argis.exampleLoaded': 'Water pipes layer loaded successfully.',
    'argis.exampleLoadError': 'Error loading example layer.',
    'argis.exampleLoadErrorDetail': 'The example layer could not be loaded.',
    'argis.ccaaHidden': 'Regional layer hidden.',
    'argis.loadingCcaa': 'Loading regional boundaries...',
    'argis.ccaaLoaded': 'Regional boundaries loaded.',
    'argis.ccaaTip': 'Click a region to view its province divisions.',
    'argis.ccaaLoadError': 'Error loading regional boundaries.',
    'argis.ccaaLoadErrorDetail': 'Regional boundaries could not be loaded.',
    'argis.loadingCommunity': 'Loading {{community}} and its provinces...',
    'argis.communityReady': 'Showing {{community}} with province divisions.',
    'argis.communityNoProvinces': 'No province boundaries could be loaded for {{community}}.',
    'argis.communityLoadError': 'Could not focus the selected region.',
    'argis.worldHidden': 'World layer hidden.',
    'argis.loadingWorld': 'Loading world GeoJSON...',
    'argis.worldLoaded': 'World GeoJSON loaded successfully.',
    'argis.worldLoadError': 'Error loading world layer.',
    'argis.worldLoadErrorDetail': 'The world GeoJSON could not be loaded.',
    'argis.layerUnsupported': 'The layer does not contain compatible geometries (lines, polygons or points).',
    'argis.polygonLayerLoaded': 'Polygon layer loaded (boundaries/urban areas).',
    'argis.pointLayerLoaded': 'Point layer loaded (places/settlements).',
    'argis.lineLayerLoaded': 'Line layer loaded successfully.',
    'argis.placeNotFound': 'The requested place was not found.',
    'argis.showingPlace': 'Showing: {{place}}.',
    'argis.searchPlaceError': 'That place could not be searched right now.',
    'argis.readShapefileError': 'The shapefile could not be read. Use .zip or select at least .shp + .dbf + .shx.',
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly currentLanguage = signal<LanguageCode>((localStorage.getItem(STORAGE_KEY) as LanguageCode) || 'es');

  constructor() {
    effect(() => {
      localStorage.setItem(STORAGE_KEY, this.currentLanguage());
      document.documentElement.lang = this.currentLanguage();
    });
  }

  setLanguage(language: LanguageCode): void {
    this.currentLanguage.set(language);
  }

  t(key: string, params?: Record<string, string | number>): string {
    const language = this.currentLanguage();
    const template = TRANSLATIONS[language][key] ?? TRANSLATIONS.es[key] ?? key;

    if (!params) return template;

    return Object.entries(params).reduce(
      (result, [param, value]) => result.replaceAll(`{{${param}}}`, String(value)),
      template
    );
  }
}
